/* generated by tests/genTestMacros.py. Do not edit directly. */


#undef XWCTEST_IF_MAGAOXAPP_EXEC_WRONG_USER
#ifdef XWCTEST_MAGAOXAPP_EXEC_WRONG_USER
#define XWCTEST_IF_MAGAOXAPP_EXEC_WRONG_USER(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_EXEC_WRONG_USER(line) do {} while(0)
#endif


#undef XWCTEST_IF_MAGAOXAPP_EXEC_LOG_START
#ifdef XWCTEST_MAGAOXAPP_EXEC_LOG_START
#define XWCTEST_IF_MAGAOXAPP_EXEC_LOG_START(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_EXEC_LOG_START(line) do {} while(0)
#endif


#undef XWCTEST_IF_MAGAOXAPP_EXEC_NORM
#ifdef XWCTEST_MAGAOXAPP_EXEC_NORM
#define XWCTEST_IF_MAGAOXAPP_EXEC_NORM(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_EXEC_NORM(line) do {} while(0)
#endif


#undef XWCTEST_IF_MAGAOXAPP_PID_LOCKED
#ifdef XWCTEST_MAGAOXAPP_PID_LOCKED
#define XWCTEST_IF_MAGAOXAPP_PID_LOCKED(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_PID_LOCKED(line) do {} while(0)
#endif


#undef XWCTEST_IF_MAGAOXAPP_PID_WRITE_FAIL
#ifdef XWCTEST_MAGAOXAPP_PID_WRITE_FAIL
#define XWCTEST_IF_MAGAOXAPP_PID_WRITE_FAIL(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_MAGAOXAPP_PID_WRITE_FAIL(line) do {} while(0)
#endif


