/* generated by tests/genTestMacros.py. Do not edit directly. */


#undef XWCTEST_IF_INDI_CALLBACK_VALIDATION
#ifdef XWCTEST_INDI_CALLBACK_VALIDATION
#define XWCTEST_IF_INDI_CALLBACK_VALIDATION(line) \
/* clang-format off */ \
{ line ; } /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_INDI_CALLBACK_VALIDATION(line) do {} while(0)
#endif


