/* generated by libMagAOX/app/dev/tests/genTestMacros.py */


#undef XWCTEST_IF_INDI_CALLBACK_VALIDATION
#ifdef XWCTEST_INDI_CALLBACK_VALIDATION
#define XWCTEST_IF_INDI_CALLBACK_VALIDATION(line) \
/* clang-format off */ \
(line); /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_INDI_CALLBACK_VALIDATION(line) do {} while(0)
#endif


#undef XWCTEST_IF_TELEMETER_LOGSTART
#ifdef XWCTEST_TELEMETER_LOGSTART
#define XWCTEST_IF_TELEMETER_LOGSTART(line) \
/* clang-format off */ \
(line); /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_TELEMETER_LOGSTART(line) do {} while(0)
#endif


#undef XWCTEST_IF_DOX_REF
#ifdef XWCTEST_DOX_REF
#define XWCTEST_IF_DOX_REF(line) \
/* clang-format off */ \
(line); /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_DOX_REF(line) do {} while(0)
#endif


#undef XWCTEST_IF_DMTIMINGS
#ifdef XWCTEST_DMTIMINGS
#define XWCTEST_IF_DMTIMINGS(line) \
/* clang-format off */ \
(line); /* LCOV_EXCL_LINE */ \
/* clang-format on */
#else
#define XWCTEST_IF_DMTIMINGS(line) do {} while(0)
#endif


